show databases;
create database Bill_n_Box;
use Bill_n_Box;
create table Admin(Admin_Id int (5) primary key , Name varchar (50) , Phone_No int (11) , Email_Id varchar (50) , Shop_Name varchar (20) , Shop_Address varchar(50));
create table Product (Product_Id int primary key , Name varchar (20) , category varchar (15) , Price double,Quantity int,Date varchar (10),LowQuantityNotification int );
desc Product;
create table customer (Id int primary key , Name varchar (20) , Phone double);
alter table Admin modify column Phone_No double;
create table Employee ( Id int primary key , Name varchar (20) , Phone double , Email varchar (20));
desc Employee;
create table Bill ( Invoice_Number double primary key, Product_Id double , Quantity int , Date varchar (10), Total_Ammount double);
show tables;
desc admin;
insert into admin values(12345,'Vijay Kamble',9365487023,'vijay.12@gmail.com','Vijay Stores','Vijay Stores,shop No.12,Hiramani Market,Mumbai');
select * from admin;
insert into product values(58246,'Lucky 7 Ball Pen','Pen',10,100,'09-09-2024',10);
select * from product;
desc customer;
insert into customer values(36524,'Vishnu Parab',9658741563);
select * from customer;
desc bill;
alter table bill add customer_Id int;
insert into bill values(20240902,58246,5,'02-09-2024',50,36524);
select * from bill;